In [15]:
import pandas as pd

# Extract csv content
nq_df = pd.read_csv("nq.csv")
gc_df = pd.read_csv("gc.csv")

In [16]:
# Format the date and time

nq_df['Time'] = pd.to_datetime(nq_df['Time'].astype(str).str.zfill(6), format='%H%M%S').dt.time
nq_df['Date'] = pd.to_datetime(nq_df['Date'].astype(str), format='%Y%m%d').dt.date

gc_df['Time'] = pd.to_datetime(gc_df['Time'].astype(str).str.zfill(6), format='%H%M%S').dt.time
gc_df['Date'] = pd.to_datetime(gc_df['Date'].astype(str), format='%Y%m%d').dt.date

In [17]:
# Combine date-time as single column

nq_df['Datetime'] = pd.to_datetime(nq_df['Date'].astype(str) + ' ' + nq_df['Time'].astype(str))
nq_df = nq_df[['Datetime', 'Price']].set_index('Datetime').sort_index()

In [18]:
gc_df['Datetime'] = pd.to_datetime(gc_df['Date'].astype(str) + ' ' + gc_df['Time'].astype(str))
gc_df = gc_df[['Datetime', 'Price']].set_index('Datetime').sort_index()

In [19]:
nq_df.head(10)

                        Price
Datetime
2025-03-26 00:51:00  20528.75
2025-03-26 00:52:00  20528.25
2025-03-26 00:53:00  20529.50
2025-03-26 00:54:00  20528.50
2025-03-26 00:55:00  20527.50
2025-03-26 00:56:00  20529.75
2025-03-26 00:57:00  20528.50
2025-03-26 00:58:00  20527.25
2025-03-26 00:59:00  20526.00
2025-03-26 01:00:00  20526.50

In [20]:
gc_df.head(10)

                      Price
Datetime
2025-03-26 05:01:00  3048.2
2025-03-26 05:02:00  3048.5
2025-03-26 05:03:00  3047.7
2025-03-26 05:04:00  3047.5
2025-03-26 05:05:00  3047.9
2025-03-26 05:06:00  3048.5
2025-03-26 05:07:00  3048.7
2025-03-26 05:08:00  3049.1
2025-03-26 05:09:00  3047.3
2025-03-26 05:10:00  3046.9